services:
  spark-master:
    build: .
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
      - SPARK_WORKER_MEMORY=1g
      - SPARK_EXECUTOR_MEMORY=1g
      - SPARK_WORKER_CORES=1
    ports:
      - "8080:8080"   # Spark Web UI (for monitoring)
      - "7077:7077"   # Spark master port (for worker connections)
    networks:
      - spark_net
    env_file:
      - .env

  spark-worker:
    image: apache/spark:3.5.3
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER=spark://spark-master:7077  # Connect to Spark master
      - SPARK_WORKER_MEMORY=1g
      - SPARK_EXECUTOR_MEMORY=1g
      - SPARK_WORKER_CORES=1
    depends_on:
      - spark-master
    networks:
      - spark_net
    command: "/bin/bash -c 'tail -f /dev/null'"

  # spark-worker-2:
  #   image: apache/spark:3.3.0
  #   container_name: spark-worker-2
  #   environment:
  #     - SPARK_MODE=worker
  #     - SPARK_MASTER=spark://spark-master:7077
  #     - SPARK_WORKER_MEMORY=1g
  #     - SPARK_EXECUTOR_MEMORY=1g
  #     - SPARK_WORKER_CORES=1
  #   depends_on:
  #     - spark-master
  #   networks:
  #     - spark_net

networks:
  spark_net:
    driver: bridge

